spring:
  application:
    name: PACKAGER-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      default: http://localhost:8761
    enabled: true
    register-with-eureka: true

server:
  port: 8085

